name: Publish docs via GitHub Pages
on: [push, workflow_dispatch]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Generate docs
        run: |
          pip install "jinja2>=2.10" mkdocs-material
          sudo gem install html-proofer
          tools/populate-docs.sh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}